### ISSUE TITLE
O que vocês acham dessa saída?

### ISSUE THREAD

**Issue by kvnol** [css-vernon/border-radius-reverse#2]
Apareceu na minha timeline e não sei se entendi muito bem a proposta, mas consegui fazer um border-radius reverso usando o before do elemento. Qual seria a ideia de vocês para contornar isso de uma vez?

![image](https://user-images.githubusercontent.com/3299130/31530813-56009cb0-afb9-11e7-8b2d-e850894759c3.png)

``` CSS
.element:before {
    content: "";
    position: absolute;
    left: -11px;
    bottom: 0;
    width: 10px;
    height: 10px;
    background: transparent;
    border-radius: 50%;
    box-shadow: 6px 3px 0 rgb(117, 145, 255);
}
```
